### PR TITLE
eas on optimism dagster asset

### PR DESCRIPTION
**Pull request by SantiMaass**

### CODE REVIEW

**Comment by Jabolol** [comment]
Hi @SantiMaass, thanks so much for your contribution! I made a few adjustments to ensure everything runs smoothly and is fully optimized.

**Comment by ravenac95** [comment]
@SantiMaass we feel this is ready to merge now just fyi which is why we're promoting this from a draft

**Review by Jabolol — APPROVED** [review]
lgtm

**Pull request merged**
